### ISSUE TITLE
Application doesn't start

### ISSUE THREAD

**Issue by koshisan** [A3yuu/FingerTruckerOSC#3]
Hi,

unfortunately, the documentation seems to be a bit unclear how things should look if the software is actually working. When I am starting FingerOSC.exe there is no window shown. However, I can tell that a task is running from Taskmanager.
I am not sure if this is normal?
When launchin VRChat while the FingerOSC.exe task is running, it takes a very, very long time to start - it also will always start in Desktop mode, no way to launch into VR...

Is there anything I can do to debug this further?

Thank you very much!

**Comment by A3yuu** [comment]
起動するとウィンドウ(Unityの制約上どうしても出てしまう純粋なUnity画面)が出るのが正常です。
ごめんなさいそのバグの原因はわからない。

**Comment by koshisan** [comment]
変です。 SteamVR が実行される_前_に起動すると、ウィンドウが表示され、すべてが正常に起動するように見えます。 しかし、ドキュメントに従って最初に ALVR を起動すると、ALVR は SteamVR 自体を起動し、その状態で FingerOSC.exe を起動しようとすると、上記のように動作します...

**Comment by A3yuu** [comment]
報告ありがとう。助かります！
しかし、申し訳ない。現象が再現できず、こちらではALVR実行後でもウィンドウが表示されます。
一旦リリースノートに注記を追加しました。

**Comment by koshisan** [comment]
私にとって、問題は何とか解決したようです。 数週間（およびその他の変更）後に再試行しましたが、現在は機能しています。 残念ながら、何が原因なのかわかりません...

**Comment by A3yuu** [comment]
うごいたようなのでクローズします
